brew "antidote"
brew "cmake"
brew "ctop"
brew "fnm"
brew "fzf"
brew "htop"
brew "imagemagick"
brew "lua-language-server"
brew "luarocks"
brew "neovim"
brew "podman"
brew "tmux"
brew "urlview"
brew "wget"

cask "alacritty", args: { no_quarantine: true }
