brew "antidote"
brew "cmake"
brew "docker"
brew "fnm"
brew "fzf"
brew "htop"
brew "imagemagick"
brew "lua-language-server"
brew "luarocks"
brew "neovim"
brew "pyenv"
brew "tmux"
brew "wget"

cask "alacritty", args: { no_quarantine: true }
