return {
  'https://github.com/nvim-treesitter/nvim-treesitter',
  lazy = false,
  build = ':TSUpdate',
  opts = {
    ensure_installed = {
      'bash',
      'editorconfig',
      'java',
      'javascript',
      'json',
      'lua',
      'markdown',
      'markdown_inline',
      'python',
      'regex',
      'toml',
      'typescript',
      'vim',
      'vimdoc',
      'yaml',
    },
    highlight = { enable = true },
    indent = { enable = true },
  },
}
